# Generated by Django 4.2.4 on 2023-08-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='psition',
            field=models.IntegerField(unique=True, verbose_name='موقعیت'),
        ),
    ]
