# Generated by Django 4.2.4 on 2023-08-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent__id', 'psition'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
    ]
