# Generated by Django 4.2.4 on 2023-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'پیش\u200cنویس'), ('p', 'منتشرشده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], default='d', max_length=1, verbose_name='وضعیت انتشار'),
        ),
    ]
