# Generated by Django 4.2.4 on 2023-09-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_is_special_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='general', max_length=100, unique=True, verbose_name='آدرس دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='عمومی', max_length=200, verbose_name='عنوان دسته\u200cبندی'),
        ),
    ]
