# Generated by Django 4.2.4 on 2023-09-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_ipaddress_post_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hits',
        ),
    ]
