# Generated by Django 4.2.4 on 2023-09-05 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_remove_post_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.ipaddress', verbose_name='آدرس آی\u200cپی')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post', verbose_name='پست')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='posts.PostHit', to='posts.ipaddress', verbose_name='بازدید'),
        ),
    ]
