# Generated by Django 4.2.4 on 2023-09-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_is_author_user_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='Avatar.png', upload_to='post/images', verbose_name='تصویر'),
        ),
    ]
